name = "_"
downloads-dir = "$DOWNLOAD_DIR/firefox"
watch-cmds = [ "mpv $XDG_CONFIG_HOME/himalaya/zdroj.mp3" ]

[rruziro]
default = true

name = "rruziro"
email = "rruziro@gmail.com"
mailboxes = { inbox = "INBOX", sent  = "[Gmail]/Sent Mail", draft = "[Gmail]/Drafts" }

smtp-host = "smtp.gmail.com"
smtp-port = 465
smtp-login = "rruziro@gmail.com"
smtp-passwd-cmd = "pass show emails/mail_client_gmail"

imap-host = "imap.gmail.com"
imap-port = 993
imap-login = "rruziro@gmail.com"
imap-passwd-cmd = "pass show emails/mail_client_gmail"

[donte]
name = "donte"
email = "donte@420blaze.it"

smtp-host = "mail.cock.li"
smtp-port = 465
smtp-login = "donte@420blaze.it"
smtp-passwd-cmd = "pass show emails/donte | head -1"

imap-host = "mail.cock.li"
imap-port = 993
imap-login = "donte@420blaze.it"
imap-passwd-cmd = "pass show emails/donte | head -1"
