#!/bin/sh

# Exit on error or undefined variable
set -eu

STATE_FILE="$HOME/.local/init_state"

# Append a checkpoint to the state file
set_done() { printf "%s\n" "$1" >> "$STATE_FILE" }

# Check if a checkpoint is present
is_done() { grep -qx "$1" "$STAATE_FILE" 2>/dev/null }

# Ensure state file exists
init_state() {
    mkdir -p "$(dirname "$STATE_FILE")"
    touch "$STATE_FILE"
}

# Panic with error
die() { echo "Error: $*" >&2; exit 1; }


# Check that we haven't yet initialized the system
check_init() {
    # Make sure the home variable is set
    [ -z "$HOME" ] && die '$HOME not set.'

    # Create the initialized file
    STATE_DIR=$(dirname "$STATE_FILE")
    mkdir -p "$STATE_DIR"
    touch "$STATE_FILE"
}


# Set up the groups and shell for the current user
setup_user() {
    if is_done setup_user; then
        echo "[skip] user already set up."
        return
    fi

    echo "[run] setting up the user."

    # Set up the groups
    for i in "network" "video" "audio" "wheel" "rustusers"; do
        sudo usermod -aG "$i" "$(whoami)"
    done

    # Set up the shell
    sudo pacman -S fish
    sudo usermod -s "/usr/bin/fish" "$(whoami)"

    set_done setup_user
}


# Set up the home directory by creating expected directories and shit
setup_home() {
    if is_done "setup_home"; then
        echo "[skip] home already set up."
        return
    fi

    echo "[run] setting up home."

    create_dirs() {
        for i in $@; do echo "$HOME/$i"; done
    }

    SHARE=".local/share"
    SANDBOX="$SHARE/sandbox"

    # Create the primary home directories
    create_dirs "documents" "pictures" ".local/bin" ".config" ".cache" ".ssh"
    create_dirs "$SHARE" "$SANDBOX"

    # Create the pictures directory
    create_dirs "pictures/screens" "pictures/wallpapers"

    # Create some other directories. These may not be used but I expect them to
    # at least exist in case I do use them eventually.
    create_dirs "documents/code/packages/tools" "documents/books"
    create_dirs "$SHARE/dnet" "$SHARE/gnupg" "$SHARE/password_database"

    # Create the sandbox directories
    create_dirs "$SANDBOX/firefox" "$SANDBOX/musescore/recording" \
        "$SANDBOX/transmission"

    # Set up the firefox sandbox
    create_dirs "$SHARE/downloads" "$SANDBOX/firefox/Downloads"
    ln -sf "./Downloads" "$HOME/$SANDBOX/firefox/Desktop"
    ln -sf "$HOME/$SANDBOX/firefox/Downloads" "$HOME/$SHARE/downloads/firefox"

    set_done "setup_home"
}


# Install dotfiles, scripts and set up the configuration
install_dotfiles() {
    echo "[run] installing dotfiles."

    # Start by installing the essentials
    sudo pacman -S --noconfirm --needed git openssh

    # Generate a new key
    if ! is_done "dotfiles_keygen"; then
        ssh-keygen -t ed25519
        set_done "dotfiles_keygen"
    else
        echo "[skip] ssh key already generated."
    fi

    # Wait for the user to import the keys into GitHub
    echo "Import the key into GitHub."
    read dummy

    # Clone the dotfiles
    DOTFILES="$HOME/documents/code/dotfiles"
    if ! is_done "dotfiles_cloned"; then
        git clone --recurse-submodules \
            'git@github.com:relativehysteria/dotfiles.git' "$DOTFILES"
        set_done "dotfiles_cloned"
    else
        echo "[skip] dotfiles already cloned."
    fi

    # Link the .config directory
    if ! is_done "dotfiles_linked"; then
        for i in "$DOTFILES/.config"/*; do
            ln -sf "$i" "$HOME/.config/"
        done

        # Link this thing
        ln -sf "$DOTFILES/prace" "$HOME/.local/share/prace"
    else
        echo "[skip] dotfiles already linked."
    fi
}

# Install the base packages
install_packages() {
    if is_done "packages_installed"; then
        echo "[skip] packages already installed"
        return
    fi

    echo "[run] installing packages."

    # Create a snapshot of the packages from dotfiles so the user can configure
    # it as they please
    PKG_FILE="/tmp/packages"
    cp "$HOME/documents/code/dotfiles/packages" "$PKG_FILE"

    # Wait for the user to edit the file
    echo "Edit '$PKG_FILE' to keep the packages you know you want installed."
    read dummy

    # Install the packages
    sudo pacman -S --needed - < "$PKG_FILE"

    set_done "packages_installed"
}

# Final reminder for what has to be done that hasn't been done yet
final_reminder() {
    echo "Don't forget to set up syslog, dns and a firewall!"
    echo "Use 'update_rust' to install/update rust."
    echo "Use 'update_discord' to install/update discord."
}

check_init
setup_groups
setup_home
install_dotfiles
install_packages
final_reminder
