#!/bin/sh

mpd         & # music
xcompmgr    & # transparency
xset r rate 150 75  & # speed xrate up
$XDG_CONFIG_HOME/fehbg  & # wallpaper
setxkbmap -option caps:swapescape  & # swap escape and caps
[ $(pgrep himalaya) ] || himalaya watch  & # email

# start the WM
exec dbus-launch --exit-with-session $WM
