k9s:
  refreshRate: 2
  maxConnRetry: 5
  enableMouse: false
  headless: true
  logoless: true
  crumbsless: true
  readOnly: true
  noExitOnCtrlC: false
  noIcons: false
  skipLatestRevCheck: false
  logger:
    tail: 1000
    buffer: 5000
    sinceSeconds: 3600
    fullScreenLogs: false
    textWrap: false
    showTime: false
  currentContext: k8s-test-4
  currentCluster: k8s-test-4
  clusters:
    cileni-dev.oa:
      namespace:
        active: kube-system
        lockFavorites: false
        favorites:
        - all
        - kube-system
        - default
      view:
        active: deployments
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
    cileni-stable.ko:
      namespace:
        active: kube-system
        lockFavorites: false
        favorites:
        - all
        - kube-system
        - default
      view:
        active: pod
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
    cileni-stable.oa:
      namespace:
        active: all
        lockFavorites: false
        favorites:
        - all
        - kube-system
        - default
      view:
        active: pod
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
    k8s-test-1:
      namespace:
        active: all
        lockFavorites: false
        favorites:
        - default
      view:
        active: pod
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
    k8s-test-4:
      namespace:
        active: all
        lockFavorites: false
        favorites:
        - cloud-init-settings
        - kube-public
        - all
        - kube-system
        - default
      view:
        active: machines
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
    kube1.ko:
      namespace:
        active: sandbox
        lockFavorites: false
        favorites:
        - sandbox
        - default
      view:
        active: nodes
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
    kube1.ng:
      namespace:
        active: default
        lockFavorites: false
        favorites:
        - default
      view:
        active: pod
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
    kube2.ko:
      namespace:
        active: sklik-vydej-production
        lockFavorites: false
        favorites:
        - sklik-vydej-production
        - cileni-stable
        - cileni-dev
        - user-profile-master
        - default
      view:
        active: contexts
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
    kube2.ng:
      namespace:
        active: user-profile-production
        lockFavorites: false
        favorites:
        - user-profile-production
        - default
      view:
        active: deployments
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
    user-profile-dev.ko:
      namespace:
        active: all
        lockFavorites: false
        favorites:
        - all
        - cileni-kubeflow
        - cert-manager
        - user-profile-master
        - default
      view:
        active: pod
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
    user-profile.ko:
      namespace:
        active: all
        lockFavorites: true
        favorites:
        - all
      view:
        active: jobs
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
    user-profile.ng:
      namespace:
        active: user-profile-production
        lockFavorites: true
        favorites:
        - all
      view:
        active: namespaces
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
  screenDumpDir: /tmp/k9s-screens-ruzickar
