#!/bin/sh

wallpaper_dir="$HOME/pictures/wallpapers/asdf"

# Get list of active monitors
outputs=$(swaymsg -t get_outputs | jq -r '.[] | select(.active) | .name')

killall swaybg

for output in $outputs; do
    random_image=$(find "$wallpaper_dir" -type f | shuf -n 1)
    echo $output
    swaybg -o "$output" -i "$random_image" -m fill &
done
