#!/bin/sh

if [ "$(hostname)" = "elise" ]; then
    wallpaper_dir="$HOME/pictures/wallpapers/videogame_locations"
else
    wallpaper_dir="$HOME/pictures/wallpapers/"
fi

# Get list of active monitors
outputs=$(swaymsg -t get_outputs | jq -r '.[] | select(.active) | .name')

killall swaybg

for output in $outputs; do
    random_image=$(find "$wallpaper_dir" | shuf -n 1)
    echo "$output | $random_image"
    swaybg -o "$output" -i "$random_image" -m fill &
done
