#!/bin/sh

wingap=0
border_width=0
color0='#000000'
color1='#3B2668'

bspc monitor DisplayPort-2 -d 1 2 3 4 5
bspc monitor HDMI-A-0 -d 6 7 8 9 10

bspc config border_width "$border_width"
bspc config window_gap   "$wingap"

bspc config split_ratio  "0.5"

bspc config focused_border_color "$color1"
bspc config active_border_color  "$color0"
bspc config normal_border_color  "$color0"

bspc config top_padding    "-$wingap"
bspc config bottom_padding "-$wingap"
bspc config left_padding   "-$wingap"
bspc config right_padding  "-$wingap"

bspc config automatic_scheme "alternate"

bspc config focus_follows_pointer "true"

setsid st
