#!/bin/sh
rm -rf "$HOME/"{Steam,.steam,.mozilla,.dbus,.pulse-cookie,.pki,.gnome,.kde,.python_history,Downloads,.wget-hsts,.BurpSuite,.java,.gem}

# *.log isn't cleared because that could be counter productive
rm -f ./{*.aux,*.ctn,*.idx,*.ilg,*.ind}
