#!/usr/bin/env python

from time import sleep
from datetime import timedelta

from sys import argv

length = int(argv[1])
inpfile = argv[2]

with open(inpfile) as f:
    inp = f.read()

def formatted(delta) -> str:
    formatted_delta = "{:0>2}:{:02}:{:02},{:03}" \
        .format(int(delta.seconds // 3600),
                int((delta.seconds % 3600) // 60),
                int(delta.seconds % 60),
                int(delta.microseconds / 1000))
    return formatted_delta

inp = '\n\n'.join(inp.split("\n\n")[1:])

verse_duration = length / len(inp.split('\n'))

current = 0
time = timedelta(seconds=0)
for verse in inp.split('\n'):
    prev_time = time
    time += timedelta(seconds=verse_duration)

    if len(verse) == 0:
        continue

    print(f"{current}\n{formatted(prev_time)} --> {formatted(time)}\n{verse}\n")
    current += 1
