#!/bin/sh
delay=40
logfile="$XDG_CACHE_HOME/radio.log"

while true; do
    # Logfile has to exist and be writable
    if ! [ -f "$logfile" ]; then
        touch "$logfile"
        ! [ $? = 0 ] && exit
    fi

    # Only do stuff on song change
    [ "$current" = "$(mpc current)" ] && sleep $delay && continue

    current="$(mpc current)"

    # Don't write/echo empty lines
    [ "$current" = "" ] && sleep $delay && continue

    grep "$current" "$logfile" &> /dev/null
    if [ $? = 1 ]; then
        echo "$current" >> "$logfile"
        echo -e "\033[92mNEW>\e[0m $current"
    else
        echo -e "\033[31mOLD>\e[0m $current"
    fi

    current="$(mpc current)"
    sleep $delay
done
