#!/bin/sh

POEMDIR="$HOME/documents/textfiles/poems"

# Get the path to a random poem
poem=$(find "$POEMDIR" | grep .txt | shuf | tail -1)

# Get the date the poem was last edited
edit_date=$(stat -c %w $poem | awk '{print $1}')

# Get the name of the collection
path_parts=$(echo "$poem" | tr '/' ' ')
collection=$(echo "$path_parts" | awk '{print $(NF-2)}')

# Get the path to the primary latex file
tex_file="$POEMDIR/$collection/LATEX/poetry.tex"

# Get the name of the whole book and strip the newcommand stuff
collection=$(grep ".newcommand{.booktitle}{" "$tex_file")
collection="${collection:24:-1}"

# Print the collection info
echo "Collection: $collection"

# Print the poem
echo && echo -n "($edit_date) " && cat "$poem"
