#!/bin/sh
name="$(git config --global user.name)"

primary="relativehysteria"

if [ "$name" = "$primary" ]; then
    git config --global user.name "Růžička, Rostislav"
    git config --global user.email "rostislav.ruzicka@firma.seznam.cz"
    echo "switched to seznam"
else
    git config --global user.name "relativehysteria"
    git config --global user.email "rruziro@gmail.com"
    echo "switched to $primary"
fi
