[general]
import = [
    "colorscheme.toml"
]

[window]
opacity = 0.8
unfocused_opacity = 0.7

[font]
normal = { family = "Fira Code" }
size = 9

[keyboard]
bindings = [
    { key = "C",        mods = "Alt|Shift", action = "Copy"             },
    { key = "V",        mods = "Alt|Shift", action = "Paste"            },
    { key = "D",        mods = "Alt|Shift", action = "IncreaseFontSize" },
    { key = "F",        mods = "Alt|Shift", action = "DecreaseFontSize" },
    { key = "Q",        mods = "Alt|Shift", action = "ResetFontSize"    },
    { key = "PageUp",   mods = "Shift",     action = "ScrollPageUp"     },
    { key = "PageDown", mods = "Shift",     action = "ScrollPageDown"   },
    { key = "K",        mods = "Alt|Shift", action = "ScrollLineUp"     },
    { key = "J",        mods = "Alt|Shift", action = "ScrollLineDown"   },
    { key = "Enter",    mods = "Alt|Shift", action = "CreateNewWindow"  },
]
